### ISSUE TITLE
Special Cases for NAME_PATTTERN regex

### ISSUE THREAD

**Issue by CodyCBakerPhD** [dandi/dandi-schema#129]
Hey all, minor suggestion here.

We're in the process of figuring out what a 'best practice' might be for experimenter name formats in NWBFiles and our investigation lead us to this line in your schema that I presume defines the DANDI standard, at least for adding associated contributors on the DANDISet level:

https://github.com/dandi/dandi-schema/blob/ffa49ef5dc84bc5a234fbc9ca9ba04b872539893/dandischema/models.py#L48

Just wanted to point out that regex pattern fails to match a case of apostrophe's in names, such as

```python
import re

pattern=r"^([\w\s\-]+),\s+([\w\s\-\.]+)$"
string="O'Baker, Cody"

re.fullmatch(pattern=pattern, string=string)
```

and also allows numerical values in names like

```python
import re

pattern=r"^([\w\s\-]+),\s+([\w\s\-\.]+)$"
string="Baker2, Cody1"

re.fullmatch(pattern=pattern, string=string)
```

though maybe you do something to account for these in downstream usages of `Person` objects? Couldn't really track it down that far.

Anyways, just wanted to let you know, happy to help fix it if desired, too.

**Comment by satra** [comment]
this looks like an old version you are referring to. the apostrophe was adjusted in a release a few versions back:

https://github.com/dandi/dandi-schema/blob/master/dandischema/models.py#L60

however, it requires an ascii apostrophe and not any of the unicode ones.

we should perhaps  removed digits, but there are some weird names with digits on the planet. names are a regex nightmare :)

**Comment by CodyCBakerPhD** [comment]
> this looks like an old version you are referring to. 

Ah, right you are! Thanks for clarifying

> we should perhaps remove digits, but there are some weird names with digits on the planet. names are a regex nightmare :)

Indeed, I can appreciate that - in my experience at least, any 'numbers' are usually appended in similar ways to middle names/initials in your pattern, *e.g.*, "Baker, Cody III", so as long as they use roman numerals it would be fine. Either way, your call on how much freedom to allow

**Comment by bendichter** [comment]
The real question is: could X Æ A-12 Musk use the archive?
