### ISSUE TITLE
dandischema installed from conda-forge has version 0.0.0 when checked by pip

### ISSUE THREAD

**Issue by rly** [dandi/dandi-schema#135]
This is super minor. I know one usually does not mix conda and pip, but I do for some things, and got this odd warning:
```
# on python 3.9 on windows
conda install -c conda-forge dandi
pip check
```
Output:
```
dandi 0.39.4 has requirement dandischema~=0.6.0, but you have dandischema 0.0.0.
dandi 0.39.4 has requirement etelemetry>=0.2.2, but you have etelemetry 0+unknown.
```

`conda list` shows:
```
dandischema               0.6.0              pyhd8ed1ab_0    conda-forge
```

`pip list` shows
```
dandischema         0.0.0
```

`pip install dandischema` is OK.
`conda install -c conda-forge dandischema` which installs the latest 0.7.1 also shows `dandischema         0.0.0` from `pip list`

Perhaps this is an issue with `versioningit`?

**Comment by yarikoptic** [comment]
@jwodder -- please address this issue. If versioningit is not yet in conda-forge, I guess should be fixed the same way it got fixed for heudiconv in  https://github.com/nipy/heudiconv/pull/566 (and may be after -- I recall there was a race of releases for some reason)

**Comment by jwodder** [comment]
This should hopefully be resolved by https://github.com/conda-forge/dandischema-feedstock/pull/28.
