### ISSUE TITLE
Cryptic Dandiset validation error: `digest: A non-zarr asset must have a sha2_256`

### ISSUE THREAD

**Issue by njmei** [dandi/dandi-schema#139]
Hi all,

I've been trying to upload and publish a new DANDI set but encountered a cryptic validation error on the DANDI archive website:

![image](https://user-images.githubusercontent.com/43766899/177613520-b344229c-bb00-4276-8886-b0cf7fffbc87.png)

The failing draft DANDI set in question can be found at: https://dandiarchive.org/dandiset/000288

I did use an unreleased branch of `dandi-cli` (see: https://github.com/dandi/dandi-cli/pull/1036) to upload the NWB files in the set, so maybe it's possible that is the source of this validation error? If not, additional clarification on what this validation error is and how to resolve it would be greatly appreciated!

Additional context for this issue:
https://github.com/dandi/dandi-cli/pull/1036#issuecomment-1172619284

**Comment by njmei** [comment]
Got it looks like it's already tracked so I'll close this issue then!

**Comment by yarikoptic** [comment]
note: and the underlying issue should have been resolved
