### ISSUE TITLE
Metadata generated by `to_datacite` rejected by DOI server

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandi-schema#166]
DOI creation currently fails for dandisets that include a contributor with a role of `dcite:Sponsor` ([example](https://dandiarchive.org/dandiset/000458/0.230317.0039) - note the dandiset has been published, but has no DOI due to the failed request). 

Here's the failed HTTP response returned by the DOI server:
```
{"errors":[{"source":"funderIdentifier","uid":"10.48324/dandi.000458/0.230317.0039","title":"DOI 10.48324/dandi.000458/0.230317.0039: The attribute 'funderIdentifierType' is required but missing. at line 104, column 0"}]}
```

It seems that we need to add the `funderIdentifierType` field alongside the current `funderIdentifier` we add here https://github.com/dandi/dandi-schema/blob/master/dandischema/datacite.py#L113

**Comment by yarikoptic** [comment]
info on `funderIdentifierType` : https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#192a-funderidentifiertype . Also from slack by @mvandenburgh 

>  the following dandisets have contributors with a role of dcite:Sponsor , and DOIs were minted successfully
['000004', '000029', '000121']

**Comment by satra** [comment]
will try to fix this asap. why did this not get caught by any of our schema tests, which does try to publish to the datacite dev server. are we simply missing any metadata with role sponsor?

**Comment by yarikoptic** [comment]
it was in July 2022 (after we added that functionality) that docs started to say that it is mandatory: https://github.com/datacite/schema-docs/commit/fbe12e97e4a6eb267cb6e27b49fc694b79088013#diff-2aeda6925c9fa93b827818f675b0736cc94ae31bd230c860f9e498c7db5c0821R49 and that page https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#192a-funderidentifiertype lists no such restriction and `Occurrence: 0-1` which I guess makes it optional.

I would say -- recent breaking change... looking more

**Comment by yarikoptic** [comment]
We got this case triggered again!  Fresh sentry email contained

```
   Oct. 10, 2023, 6:09 p.m. UTC
   Mute this alert This email was triggered by Send a notification for new
   issues

   Issue
           {"errors":[{"source":"funderIdentifie...
   error   dandiapi.api.tasks.publish_dandiset_task

         Oct. 10, 2023, 6:09:29 p.m. UTC
           {'data': {'id': '10.48324/dandi.00057...
   error   dandiapi.api.tasks.publish_dandiset_task

         Oct. 10, 2023, 6:09:29 p.m. UTC
           Failed to create DOI 10.48324/dandi.0...
   error   dandiapi.api.tasks.publish_dandiset_task

         Oct. 10, 2023, 6:09:28 p.m. UTC
```

the first error is about

```json
[{"source":"funderIdentifier","uid":"10.48324/dandi.000576/0.231010.1811","title":"DOI 10.48324/dandi.000576/0.231010.1811: The attribute 'funderIdentifierType' is required but missing. at line 102, column 0"}]
```

**Comment by yarikoptic** [comment]
note in above case -- version is produced but DOI is not dereferencing as it should for https://doi.org/10.80507/dandi.123456/0.123456.1234 . So whenever the issue is addressed we might need to go through all versions of dandisets and check if all of their DOIs dereference.

**Comment by satra** [comment]
@mvandenburgh @djarecka - has this now been resolved?

**Comment by mvandenburgh** [comment]
> @mvandenburgh @djarecka - has this now been resolved?

Yes. (Relevant PR: https://github.com/dandi/dandi-schema/pull/167)
