### ISSUE TITLE
JSON-LD context can't dereference: schema.dandiarchive.org doesn't exist :(

### ISSUE THREAD

**Issue by sneakers-the-rat** [dandi/dandi-schema#206]
the yaml-ld `dandiset.yaml` file includes a `'@context': https://raw.githubusercontent.com/dandi/schema/master/releases/0.6.0/context.json`

that context creates `"dandi": "http://schema.dandiarchive.org/"` prefix, from here:

https://github.com/dandi/dandi-schema/blob/68f4d1e597926ac095b36db26a1033f6de621bd0/dandischema/metadata.py#L33-35

however http://schema.dandiarchive.org doesn't exist, so all the `dandi:` terms can't be dereferenced :(

there are [no DNS records](https://dnschecker.org/all-dns-records-of-domain.php?query=schema.dandiarchive.org&rtype=ALL&dns=google) for the subdomain, so it doesn't seem like just a server going down, maybe just a typo and that is supposed to point somewhere else?

**Comment by satra** [comment]
that is not being served at the moment. it's just a unique key for now. we had planned to put up schema docs at that url, but will wait till after linkml transition is done. json-ld doesn't require dereferencing for anything other than `@context` and the context does dereference. 

at present any of the dandi terms are simply IRIs not URLs.

**Comment by sneakers-the-rat** [comment]
fair enough! just wanted to raise if it was an accident like the domain moved or something. will just treat as a non-dereferencing IRI for now. i'll close this since there is a plan already
