### ISSUE TITLE
 INTERNAL ERROR: maximum semantic  from mypy

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-schema#223]
We starting getting those problems with mypy checking, e.g. see ones in
- https://github.com/dandi/dandi-schema/pull/222

and overall type checking was red for a week according to https://github.com/dandi/dandi-schema/actions/workflows/typing.yml 

and I found so far
- https://github.com/python/mypy/issues/12439
which was closed as there were no repro (although original submission had some example, odd).  so more digging is needed, 

the difference between versions from good to bad was

```
@@ -22,13 +22,13 @@
 pip==23.3.1
 pkgutil_resolve_name==1.3.10
 pluggy==1.4.0
-pydantic==2.5.3
-pydantic_core==2.14.6
-pytest==7.4.4
+pydantic==2.6.0
+pydantic_core==2.16.1
+pytest==8.0.0
 pytest-cov==4.1.0
 pytest-rerunfailures==13.0
 python-dateutil==2.8.2
-referencing==0.32.1
+referencing==0.33.0
 requests==2.31.0
 rfc3339-validator==0.1.4
 rfc3987==1.3.8
```

**Comment by jwodder** [comment]
@yarikoptic This may be due to a bug in pydantic's mypy plugin.  If I restrict pydantic to `<2.6` (Pydantic 2.6.0 was released on 2024-01-29), the type checking passes.
