### ISSUE TITLE
Pydantic test failure on `=dandischema-0.9.1` with `=pydantic-2.4.2` but not with newer pydantic versions.

### ISSUE THREAD

**Issue by TheChymera** [dandi/dandi-schema#228]
Full [build and test log](https://ppb.chymera.eu/c0769d.html).

It's basically these three tests:

```
FAILED dandischema/tests/test_metadata.py::test_asset - dandischema.exceptions.PydanticValidationError: [{'type': 'string_type', 'loc': ('wasAttributedTo', 0, 'sex', 'identifier'), 'msg': 'In...
FAILED dandischema/tests/test_metadata.py::test_aggregate[files1-summary1] - pydantic_core._pydantic_core.ValidationError: 1 validation error for AssetsSummary
FAILED dandischema/tests/test_metadata.py::test_aggregate[files2-summary2] - pydantic_core._pydantic_core.ValidationError: 1 validation error for AssetsSummary
```

This failure is happening with `=pydantic-2.4.2`, which I used due to [this requirement](https://github.com/dandi/dandi-schema/blob/9b9c283051aedfc7e4e1aa0ab0b5e3202e145530/setup.cfg#L33).

With newer pydantic versions, however, this issue goes away:

Tests [pass with `=pydantic-2.5.3`](https://ppb.chymera.eu/5879d8.html) and [with `=pydantic-2.6.1`](https://ppb.chymera.eu/6a153a.html).

Is the dependency version cap outdated, if so, why doesn't this show up in CI? 🤔

**Comment by jwodder** [comment]
@TheChymera `~= 2.4` means a cap of 3.0, not 2.5.  You're allowed to use the current-latest pydantic with this package.

**Comment by TheChymera** [comment]
ah, ok.
