### ISSUE TITLE
Resource type

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-schema#231]
https://github.com/dandi/dandi-schema/blob/e6cc5a06dd7f7e03e86316071ac9e541ff27d223/dandischema/models.py#L869-L900

Our current resource schema has no way of indicating what type of resource it is. This is currently a problem for me as I am trying to determine how many unique publications are associated with the data on DANDI. I need to infer the type based on the designated relation and the URL. It would be much easier for me if this infrormation were explicitly encoded. The Data Cite schema provides a [resourceType model](https://datacite-metadata-schema.readthedocs.io/en/4.5/appendices/appendix-1/resourceTypeGeneral/) that covers a lot of major resource categories. I propose we add this as an optional field to the Resource model.

**Comment by satra** [comment]
sounds good. any interest in sending a PR to add an attribute and a set of elements (see the other type enums on how that's done)?

**Comment by bendichter** [comment]
It works!

<img width="1583" alt="image" src="https://github.com/dandi/dandi-schema/assets/844306/3263d961-9061-41f9-a3ee-63c26ef2ad92">
