### ISSUE TITLE
Standardize humans names to "Last, First"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-schema#255]
Similarly we likely to pursue it at the level of BIDS:
- https://github.com/bids-standard/bids-2-devel/issues/82#issuecomment-2387463481

since without that, it is impossible to separate full name into First and Last for a more detailed schema, as e.g. in openMINDS (@lzehl).

ATM we have also just

```
    name: Optional[str] = Field(None, json_schema_extra={"nskey": "schema"})
```

and just a "convention" stated somewhere to possibly enter as "Last, First".

WDYT @satra -- should we aim to harmonize or at least going forward to more explicitly encourage `Last, First` form?

**Comment by satra** [comment]
that's weird. i'm sure i've seen both examples or Last, First on the meditor (which is based on json). perhaps it was adjusted sometime because of keeping the variable description more consistent. we should check.

**Comment by yarikoptic** [comment]
indeed, I was "mislead" we do indeed have 

```python
class Person(Contributor):
    ...
    name: str = Field(
        description="Use the format: familyname, given names ...",
        pattern=NAME_PATTERN,
        json_schema_extra={"nskey": "schema"},
        examples=["Lovelace, Augusta Ada", "Smith, John", "Chan, Kong-sang"],
    )
```
and I guess I was citing the 

```python
class Contributor(DandiBaseModel):
    ...
    name: Optional[str] = Field(None, json_schema_extra={"nskey": "schema"})
```

which is the base class for `Person` where we restrict `name` to follow the `Last, First` convention. And as `Contributor` could also be the `Organization` where indeed it doesn't make sense to enforce `Last, First` -- it is all "ok"

but also we have

```python
class RelatedParticipant(DandiBaseModel):
    identifier: Optional[Identifier] = Field(
        None, json_schema_extra={"nskey": "schema"}
    )
    name: Optional[str] = Field(
        None,
        title="Name of the participant or subject",
        json_schema_extra={"nskey": "schema"},
    )
```
where hopefully we would not need `Last, First` and it could potentially be the animal name I guess..

But I think in general we are ok, sorry for the noise!
